# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5c139f778fad52f42553de4ef3c9372a9777fee8b1945ae7b09e7efa5295b24ce70559f941cbb012f97f0c2d5940dbe6619fd8c5a4c5d5db4a1a1667f68053a

test:
  secret_key_base: 85aba4f0d9fa9279682bf685b671974c80f46272d3743263047c9af4171379af7e82d62ba4acdcee6ce78b8b1180a1910eb92992974cdb0e152762d5ade42008

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
